name: Noureddin 124
on: 
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Realase version'     
        required: true
      tag:
        description: 'tag'
        required: true 
      developmentVersion:
        description: 'development Version (snapshot)'
        required: true 

# jobs:
#   log-the-inputs:
#     runs-on: ubuntu-latest
#     steps:
#       - run: |
#           echo "Log level: $VERSION"
#           echo "Tags: $TAGS"
#           echo "Environment: $ENVIRONMENT"
#         env:
#           VERSION: ${{ github.event.inputs.releaseVersion }}
#           TAGS: ${{ github.event.inputs.tag }}
#           ENVIRONMENT: ${{ github.event.inputs.developmentVersion }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: config git 
      run: git config --global user.name "NOUREDDIN"  && git config --global user.email "noureddin.souad@damanesign.ma"
    - name: Prepare to GitHub Packages Apache Maven
      run: mvn release:prepare   -DreleaseVersion=$VERSION   -DdevelopmentVersion=$DEV_VERSION   -Dtag=$TAG -Dresume=false
      env:
        GITHUB_TOKEN: ${{ github.token }}
        VERSION: ${{ github.event.inputs.releaseVersion }}
        TAG: ${{ github.event.inputs.tag }}
        DEV_VERSION: ${{ github.event.inputs.developmentVersion }}
    - name: Publish to GitHub Packages Apache Maven
      run: mvn release:perform -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Rollback in error
      if: ${{ failure() }}
      run: mvn release:rollback -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
    # - uses: "marvinpinto/action-automatic-releases@latest"
    #   with:
    #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
    #     prerelease: false
