name: publish package to s3
on: 
  registry_package:
    action:
      - published
      - updated
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1