name: publish package to s3
on: 
  registry_package:
    action:
      - published
      - updated
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8git 
        server-id: github # UNABLE TO TRIGGER THIS EVENTS  https://stackoverflow.com/questions/69886051/github-registry-package-event-doesn-t-trigger
        settings-path: ${{ github.workspace }} # location for the settings.xml file https://github.com/actions/create-release/pull/115